sudo: required
dist: xenial
language: python
python:
  - "3.7.1"
services:
  - docker
  - postgresql
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
  - pip install pipenv
  - pipenv install
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test
  - create table migrate_version(repository_id varchar(250) not null, repository_path text, version integer);
  - exit
  - python migrations/manage.py upgrade

script: 
  - pytest
  - docker build -t cbrzn/camporota_backend .
  - docker tag cbrzn/camporota_backend registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push cbrzn/camporota_backend;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master