"""empty message

Revision ID: 086d51e573db
Revises: 0ec22b1b347a
Create Date: 2019-10-09 13:04:14.186753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '086d51e573db'
down_revision = '0ec22b1b347a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('property_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'properties', ['property_id'])
    op.drop_column('properties', 'identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('identifier', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_column('properties', 'property_id')
    op.drop_column('properties', 'date_updated')
    op.drop_column('properties', 'date_created')
    # ### end Alembic commands ###
