"""empty message

Revision ID: 0b311a7b7739
Revises: 32439c96e125
Create Date: 2020-02-23 21:14:19.828423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b311a7b7739'
down_revision = '32439c96e125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('rooms', sa.Integer(), nullable=False))
    op.drop_column('properties', 'bathroom')
    op.drop_column('properties', 'room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('room', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('bathroom', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('properties', 'rooms')
    op.drop_column('properties', 'bathrooms')
    # ### end Alembic commands ###
