"""empty message

Revision ID: 32439c96e125
Revises: bd7bc2ea7e41
Create Date: 2020-02-23 17:51:23.867193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32439c96e125'
down_revision = 'bd7bc2ea7e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('bathroom', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('bond', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('common_zones', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('community_fees', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('contract_time', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('equipped_kitchen', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('floor_number', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('furnished', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('heating', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('orientation', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('pets', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('room', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('square_meters', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('properties', 'square_meters')
    op.drop_column('properties', 'room')
    op.drop_column('properties', 'pets')
    op.drop_column('properties', 'orientation')
    op.drop_column('properties', 'heating')
    op.drop_column('properties', 'furnished')
    op.drop_column('properties', 'floor_number')
    op.drop_column('properties', 'equipped_kitchen')
    op.drop_column('properties', 'contract_time')
    op.drop_column('properties', 'community_fees')
    op.drop_column('properties', 'common_zones')
    op.drop_column('properties', 'bond')
    op.drop_column('properties', 'bathroom')
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###
