"""empty message

Revision ID: 671ec7d07078
Revises: 086d51e573db
Create Date: 2019-10-09 14:30:20.925782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '671ec7d07078'
down_revision = '086d51e573db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('properties', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('properties', 'date_updated')
    op.drop_column('properties', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'time_updated')
    op.drop_column('properties', 'time_created')
    # ### end Alembic commands ###
