"""empty message

Revision ID: c82d1d1be5d3
Revises: 0b311a7b7739
Create Date: 2020-02-24 13:49:22.536584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82d1d1be5d3'
down_revision = '0b311a7b7739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'bond',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'common_zones',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'community_fees',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'contract_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'equipped_kitchen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('properties', 'floor_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'furnished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('properties', 'heating',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('properties', 'orientation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'pets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('properties', 'rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'square_meters',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'square_meters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'pets',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('properties', 'orientation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'heating',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('properties', 'furnished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('properties', 'floor_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'equipped_kitchen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('properties', 'contract_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'community_fees',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'common_zones',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'bond',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
