"""empty message

Revision ID: ce40a2f1749f
Revises: e8352a0d0864
Create Date: 2019-11-07 10:09:08.920596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce40a2f1749f'
down_revision = 'e8352a0d0864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_property_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'properties', ['property_id'], ['property_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_property_id_fkey', 'images', 'properties', ['property_id'], ['property_id'])
    # ### end Alembic commands ###
